# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 831f40eb57ba5680fb03fd17dc3b0660bac225ca6672fcdb8e9219a263ddaea6e56b6ce4880b892ab5995614dc9715ba96d70c0af0dc9205eac95c097d711b0d

test:
  secret_key_base: 12f8286f6fe9246e3053f5419e681649454ff5256ea5a7cce28078a8cf7d4d2bebf9ab9164d0b9f93278c8e5824cf17b89755e4b1068b4049936a0ba10d08247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
